version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=cncf-vitess-project@cncf.io"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: bridge

  backend-frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: "arewefastyet-backend-frontend"
    container_name: "backend-frontend"
    volumes:
      - "./exec/:/exec"
      - "./config/prod/:/config/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-frontend.rule=Host(`benchmark.vitess.io`)"
      - "traefik.http.routers.backend-frontend.entrypoints=websecure"
      - "traefik.http.routers.backend-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.backend-frontend.loadbalancer.server.port=8080"
    network_mode: bridge