# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Make sure vtctld is stopped
  when: clean_vtctld | bool
  include_role:
    name: "vtctld"
    tasks_from: clean

- name: Make sure vtgate is stopped
  when: clean_vtgate | bool
  include_role:
    name: "vtgate"
    tasks_from: clean

- name: make sure vttablet is stopped
  when: clean_vttablet | bool
  include_role:
    name: "vttablet"
    tasks_from: "clean"

- name: Format the Drive
  filesystem:
    device: '/dev/{{ storage_device.partition }}'
    fstype: xfs

- name: Mount the Drive
  mount:
    path: /vt
    src: '/dev/{{ storage_device.partition }}'
    fstype: xfs
    state: unmounted
  when: storage_device is defined

- name: Clean vtdataroot
  file:
    path: '{{ vitess_root }}'
    state: absent

- name: create folder for mount
  file:
    path: /vt
    state: directory
    recurse: yes

- name: Mount the Drive
  mount:
    path: /vt
    src: '/dev/{{ storage_device.partition }}'
    fstype: xfs
    state: mounted
  when: storage_device is defined
