# Copyright 2021 The Vitess Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
all:
  hosts:
    147.75.87.247:
      storage_device:
        device: nvme0n1
        partition: nvme0n1p1
  vars:
    arewefastyet_git_repo: "https://github.com/vitessio/arewefastyet.git"
    arewefastyet_git_version: "HEAD"
    macrobenchmark_vschema_oltp: "./vitess-benchmark/sysbench.json"
    macrobenchmark_vschema_tpcc: "./vitess-benchmark/tpcc_vschema.json"
    macrobenchmarks_local_config: "../config/test_gen4_oltp_query_stats.yaml"
    cell: local
    keyspace: main
    provision: 1
  children:
    macrobench:
      hosts:
        147.75.87.247:
      vars:
        vtgate_web_ports: "15001,15002,15003,15004,15005,15006"
    sysbench:
      hosts:
        147.75.87.247:
    prometheus:
      hosts:
        147.75.87.247:
    etcd:
      hosts:
        147.75.87.247:
    vtctld:
      hosts:
        147.75.87.247:
    vtgate:
      vars:
        vtgate_query_cache_size: 1000
        vtgate_max_goproc: 12
      hosts:
        147.75.87.247:
          gateways:
            - id: 1
              port: 15001
              mysql_port: 13306
              grpc_port: 15306
            - id: 2
              port: 15002
              mysql_port: 13307
              grpc_port: 15307
            - id: 3
              port: 15003
              mysql_port: 13308
              grpc_port: 15308
            - id: 4
              port: 15004
              mysql_port: 13309
              grpc_port: 15309
            - id: 5
              port: 15005
              mysql_port: 13310
              grpc_port: 15310
            - id: 6
              port: 15006
              mysql_port: 13311
              grpc_port: 15311
    vttablet:
      vars:
        vitess_memory_ratio: 0.6
        vttablet_query_cache_size: 10000
        vttablet_max_goproc: 24
      hosts:
        147.75.87.247:
          tablets:
            - id: 1001
              keyspace: main
              shard: -80
              pool_size: 500
              transaction_cap: 2000
              port: 16001
              grpc_port: 17001
              mysql_port: 18001
              mysqld_exporter_port: 9104
            - id: 2001
              keyspace: main
              shard: 80-
              pool_size: 500
              transaction_cap: 2000
              port: 16002
              grpc_port: 17002
              mysql_port: 18002
              mysqld_exporter_port: 9105
