name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
            ansible/*.yml
            ansible/roles

        override-deps: |
          ansible==2.10.7
          ansible-lint==4.3.7

        args: "-x 301,302,303,305,306,204,208"
