name: Deploy

on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd $HOME/arewefastyet
            git reset --hard FETCH_HEAD
            git clean -fd
            git fetch origin master
            git checkout origin FETCH_HEAD
            go build ./go/main.go
            ./supervisor/update.sh