name: Golang Unit Tests

on: [push, pull_request]

jobs:

  build:
    name: Execute all the unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: make test
