name: Golang Lint

on: [push, pull_request]

jobs:

  build:
    name: Lint all go files
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: Clean Env
        run: $(go env GOPATH)/bin/golangci-lint cache clean

      - name: Print linter version
        run: $(go env GOPATH)/bin/golangci-lint --version

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./go/... --timeout 5m